### PR TITLE
Fix map event handling

### PR DESCRIPTION
**Pull request by larahoya**
https://kantree.io/p/96d2bd51-rider?m=kanban&gt=33988&q=%23Android&v=7750#258

https://github.com/cabify/cabify_coffee/pull/965

### CODE REVIEW

**Comment by lurecas** [comment]
I think it is great! The only thing I would change is the `CameraPositionParser` name, I would name it `CameraPositionSerializer` as it is converting between data types to a JSON. Otherwise, 🔝

**Comment by cicloon** [comment]
This looks great, but just a question, why aren't you launching the zoom start event? wouldn't it be useful in the js side (I'm thinking about dropping the pin when the zoom starts)?

**Comment by larahoya** [comment]
@cicloon  I've removed it at the last moment just because I'm not going to use it.  If It could be useful I can add it easily!

**Comment by pedroduran** [comment]
cool-ok-sure-l41lUjUgLLwWrz20w

**Comment by cicloon** [comment]
🍻

**Pull request merged**
